
apiVersion: v1
kind: Service
metadata:
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  #   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "HTTP"
  #   service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
  #   service.beta.kubernetes.io/aws-load-balancer-subnets: "${subnet_ids}"
  name: amazon-service
  namespace: deployment
  labels:
    app: amazon-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: amazon-app