
apiVersion: v1
kind: Service
metadata:
  name: amazon-service
  namespace: deployment
  labels:
    app: amazon-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: amazon-app