name: Manifest Change

on:
  workflow_dispatch:
    
  push:
    paths:
      - ./manifests/deployment.yaml

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract image tag
        run: |
          IMAGE=$(grep "image:" manifests/deployment.yaml | awk '{print $2}')
          echo "Image extracted: $IMAGE"
          echo "image=$IMAGE" >> $GITHUB_ENV        

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull ${{ env.image }}


      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.image }}'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true

#      - name: Run Tests
#        run: docker run ${{ env.image }} ./run_tests.sh